# The UI kit (templates/ui-kit, lib/UiKit.psm1): a catalogue in the project's .streamhub/ui-kit/ for
# interface work (setting uiKit), and in styles/kit/ only what the pages use; its rule goes to Copilot with the UI rules; generated-looking patterns
# are reported (Guardrails Find-UiSlop). Made-up project content.
$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Import-Module (Join-Path $root 'lib\Config.psm1') -Force
Import-Module (Join-Path $root 'lib\UiKit.psm1') -Force
Import-Module (Join-Path $root 'lib\Guardrails.psm1') -Force
Import-Module (Join-Path $root 'lib\Prompts.psm1') -Force
Import-Module (Join-Path $root 'lib\Lint.psm1') -Force

Describe 'Install-UiKit' {
    $p = Join-Path $env:TEMP ('ccb-kit-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
    It 'puts the whole kit in the catalogue and only the tokens and the stylesheet in styles/kit, never overwriting the project''s tokens' {
        @(Install-UiKit $p $root) -join ',' | Should Be 'styles/kit/tokens.css,styles/kit/kit.css'
        foreach ($f in 'kit.css', 'kit.js', 'kit-charts.js', 'kit-data.js', 'kit-examples.html', 'LICENSE-kokonutui.txt', 'vendor\pdfjs\pdf.min.js', 'VERSION.txt') {
            Test-Path (Join-Path $p ".streamhub\ui-kit\$f") | Should Be $true
        }
        @(Get-ChildItem (Join-Path $p 'styles\kit') -Recurse -File).Count | Should Be 2
        (Get-Content (Join-Path $p 'styles\kit\kit.css') -TotalCount 1) | Should Match '^/\* Generated by the helper program from the UI kit'
        Test-UiKitInProject $p | Should Be $true
        [IO.File]::WriteAllText((Join-Path $p 'styles\kit\tokens.css'), ':root { --kit-accent: #224466; }')
        @(Install-UiKit $p $root).Count | Should Be 0
        [IO.File]::ReadAllText((Join-Path $p 'styles\kit\tokens.css')) | Should Match '#224466'
    }
    It 'adds a React part when the code imports it, with the script and licence it needs' {
        $r = Join-Path $env:TEMP ('ccb-kitr-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory (Join-Path $r 'src') -Force | Out-Null
        [IO.File]::WriteAllText((Join-Path $r 'package.json'), '{ "dependencies": { "react": "^19.0.0" } }')
        $null = Install-UiKit $r $root
        Test-Path (Join-Path $r '.streamhub\ui-kit\react\HoldButton.tsx') | Should Be $true
        Test-Path (Join-Path $r 'styles\kit\react') | Should Be $false
        [IO.File]::WriteAllText((Join-Path $r 'src\App.tsx'), "import { Chart } from `"../styles/kit/react/Chart`";`nimport { HoldButton } from `"../styles/kit/react/HoldButton`";")
        $u = Update-UiKitProject $r $root
        foreach ($f in 'react/Chart.tsx', 'kit-charts.js', 'LICENSE-bklit-ui.txt', 'react/HoldButton.tsx', 'LICENSE-kokonutui.txt') { $u.added -contains "styles/kit/$f" | Should Be $true }
        $u.added -contains 'styles/kit/kit.js' | Should Be $false
        $css = [IO.File]::ReadAllText((Join-Path $r 'styles\kit\kit.css'))
        $css | Should Match '\.kit-btn--hold\.is-holding::before'
        $css | Should Match '\.kit-chart__bar'
        Remove-Item $r -Recurse -Force -ErrorAction SilentlyContinue
    }
    Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
}

Describe 'Taking what the pages use from the catalogue' {
    $p = Join-Path $env:TEMP ('ccb-kitu-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
    $null = Install-UiKit $p $root
    $css = { [IO.File]::ReadAllText((Join-Path $p 'styles\kit\kit.css')) }
    It 'writes only the rules of the kit classes in use' {
        [IO.File]::WriteAllText((Join-Path $p 'index.html'), '<body class="kit-page"><div class="kit-split"><button class="kit-btn kit-btn--primary">Go</button></div></body>')
        $u = Update-UiKitProject $p $root
        $u.updated -contains 'styles/kit/kit.css' | Should Be $true
        $c = & $css
        $c | Should Match '\.kit-btn--primary \{'
        $c | Should Match '@media \(max-width: 860px\) \{ \.kit-split'
        $c | Should Not Match 'kit-search|kit-chart|kokonutui'
        @((Update-UiKitProject $p $root).updated).Count | Should Be 0   # nothing new: left as it is
    }
    It 'adds a kit script a page loads, with its licence, and the classes the script uses' {
        [IO.File]::WriteAllText((Join-Path $p 'search.html'), '<div class="kit-search" data-kit-search><input class="kit-input"></div><script src="styles/kit/kit.js"></script>')
        $u = Update-UiKitProject $p $root
        $u.added -contains 'styles/kit/kit.js' | Should Be $true
        $u.added -contains 'styles/kit/LICENSE-kokonutui.txt' | Should Be $true
        $c = & $css
        $c | Should Match '\.kit-search__list'
        $c | Should Match 'adapted from kokonutui'
    }
    It 'takes classes made in code by prefix, and leaves pdf.js out until a page loads it' {
        [IO.File]::WriteAllText((Join-Path $p 'badge.js'), 'el.className = "kit-badge kit-badge--" + tone;')
        $null = Update-UiKitProject $p $root
        & $css | Should Match '\.kit-badge--ok'
        Test-Path (Join-Path $p 'styles\kit\vendor') | Should Be $false
        [IO.File]::WriteAllText((Join-Path $p 'read.html'), '<script src="styles/kit/vendor/pdfjs/pdf.min.js"></script><script src="styles/kit/vendor/pdfjs/pdf.worker.min.js"></script><script src="styles/kit/kit-data.js"></script>')
        $u = Update-UiKitProject $p $root
        foreach ($f in 'vendor/pdfjs/pdf.min.js', 'vendor/pdfjs/pdf.worker.min.js', 'vendor/pdfjs/LICENSE-pdfjs.txt', 'kit-data.js') { $u.added -contains "styles/kit/$f" | Should Be $true }
    }
    It 'leaves a kit.css the project made itself alone' {
        [IO.File]::WriteAllText((Join-Path $p 'styles\kit\kit.css'), '.kit-btn { color: red; }')
        $null = Update-UiKitProject $p $root
        & $css | Should Be '.kit-btn { color: red; }'
    }
    It 'refuses a change by Copilot to the generated stylesheet' {
        Import-Module (Join-Path $root 'lib\Executor.psm1')
        Remove-Item (Join-Path $p 'styles\kit\kit.css')
        $null = Update-UiKitProject $p $root
        { Assert-Writable $p 'styles/kit/kit.css' } | Should Throw 'written by the helper program'
        { Assert-Writable $p 'styles/kit/tokens.css' } | Should Not Throw
    }
    Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
}

Describe 'Searching the kit catalogue' {
    It 'lets glob and grep find the catalogue, but not the rest of .streamhub or pdf.js' {
        Import-Module (Join-Path $root 'lib\Executor.psm1')
        $p = Join-Path $env:TEMP ('ccb-kits-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        $null = Install-UiKit $p $root
        [IO.File]::WriteAllText((Join-Path $p '.streamhub\issues.json'), '{ "note": "kit-search__list" }')
        Invoke-GlobAction $p '**/kit-examples.html' | Should Match '^\.streamhub/ui-kit/kit-examples\.html'
        Invoke-GlobAction $p '**/issues.json' | Should Match 'no files match'
        $g = Invoke-GrepAction $p 'kit-search__list'
        $g | Should Match '\.streamhub/ui-kit/kit-examples\.html:\d+:'
        $g | Should Match '\.streamhub/ui-kit/kit\.css:\d+:'
        $g | Should Not Match 'issues\.json'
        Invoke-GrepAction $p 'getDocument' | Should Not Match 'vendor/pdfjs'
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
    }
}

Describe 'Select-KitCss' {
    It 'keeps the used selectors of a list, used @media rules, named keyframes and a licence note once' {
        $src = "/* header */`n.kit-a { x: 1; }`n/* Parts adapted from X (MIT licence, see LICENSE-x.txt). */`n.kit-b, .kit-c:hover { y: 2; }`n@media (max-width: 9px) { .kit-b { z: 3; } .kit-d { z: 4; } }`n.kit-e .kit-b { w: 5; }`n@keyframes kit-spin { to { a: b; } }`n.kit-b { animation: kit-spin 1s; }"
        $used = New-Object 'System.Collections.Generic.HashSet[string]'; [void]$used.Add('kit-b')
        $out = Select-KitCss $src @{ classes = $used; prefixes = @() }
        $out | Should Not Match 'header|kit-a|kit-c|kit-d|kit-e'
        $out | Should Match '(?m)^\.kit-b \{ y: 2; \}'
        $out | Should Match '@media \(max-width: 9px\) \{ \.kit-b \{ z: 3; \} \}'
        $out | Should Match '@keyframes kit-spin'
        ([regex]::Matches($out, 'MIT licence')).Count | Should Be 1
    }
}

Describe 'The UI kit rule' {
    It 'goes with the UI rules while the setting is on' {
        $ids = @(& (Get-Module Prompts) { Get-PromptModules -Text 'Build a dashboard page with a table and filters' -Context @{ Paths = @('index.html'); Traits = @('web', 'code') } })
        $ids -contains 'rules:ui' | Should Be $true
        $ids -contains 'rules:uikit' | Should Be $true
    }
    It 'is left out when the setting is off' {
        Mock -ModuleName Prompts Test-UiKitOn { $false }
        $ids = @(& (Get-Module Prompts) { Get-PromptModules -Text 'Build a dashboard page with a table and filters' -Context @{ Paths = @('index.html'); Traits = @('web', 'code') } })
        $ids -contains 'rules:uikit' | Should Be $false
    }
    It 'names only classes the kit has' {
        $rule = [IO.File]::ReadAllText((Join-Path $root 'prompts\rules\uikit.md'))
        $css = [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\kit.css'))
        $line = (@($rule.Split("`n") | Where-Object { $_ -like '- Components:*' -or $_ -like '- Interactive parts*' }) -join ' ')
        foreach ($m in [regex]::Matches($line, '(?<![\w-])kit-[a-z0-9_-]+')) { $css | Should Match ([regex]::Escape('.' + $m.Value.TrimEnd('-'))) }
    }
}

Describe 'Find-UiSlop' {
    It 'reports gradient text, thick side stripes and decorative blur that a change adds' {
        $new = ".title { background: linear-gradient(90deg, red, blue); background-clip: text; }`n.note { border-left: 4px solid #c00; }`n.glass { backdrop-filter: blur(12px); }"
        $r = @(Find-UiSlop 'styles/app.css' '' $new)
        $r.Count | Should Be 3
        ($r -join ' ') | Should Match 'gradient text'
        ($r -join ' ') | Should Match 'side stripe'
        ($r -join ' ') | Should Match 'blur'
    }
    It 'reports hard-coded colours only with the kit in the project, and not in the tokens file' {
        $new = '.box { color: #333; }'
        @(Find-UiSlop 'styles/app.css' '' $new).Count | Should Be 0
        @(Find-UiSlop 'styles/app.css' '' $new -UseKit) -join ' ' | Should Match 'hard-coded colour'
        @(Find-UiSlop 'styles/kit/tokens.css' '' ':root { --kit-accent: #10069f; }' -UseKit).Count | Should Be 0
        @(Find-UiSlop 'styles/app.css' '' '.box { color: var(--kit-text); border: 1px solid var(--kit-border); }' -UseKit).Count | Should Be 0
    }
    It 'leaves lines the file already had alone' {
        $old = '.note { border-left: 4px solid #c00; }'
        @(Find-UiSlop 'styles/app.css' $old "$old`n.x { margin: 0; }").Count | Should Be 0
    }
    It 'reports hard-coded colours in markup and scripts with the kit, and leaves kit tokens and selectors alone' {
        foreach ($c in @(
            @('index.html', '<div style="color: #ff0000">Total</div>'),
            @('index.html', '<rect fill="#204060" width="4" height="4"/>'),
            @('index.html', '  .total { background: rgba(0, 0, 0, 0.2); }'),
            @('src/app.js', "ctx.fillStyle = 'rgb(10, 20, 30)';"),
            @('src/Card.tsx', '<div style={{ color: "#336699" }}>Total</div>'))) {
            @(Find-UiSlop $c[0] '' $c[1] -UseKit) -join ' ' | Should Match 'hard-coded colour'
            @(Find-UiSlop $c[0] '' $c[1]).Count | Should Be 0
        }
        foreach ($c in @(
            @('src/app.js', "document.querySelector('#main').hidden = true;"),
            @('src/app.js', "el.style.background = 'var(--kit-chart-1)';"),
            @('index.html', '<div style="color: var(--kit-text)">Total</div>'),
            @('styles/kit/kit-charts.js', "var x = '#ffffff';"),
            @('README.md', 'Colour #ffffff'))) {
            @(Find-UiSlop $c[0] '' $c[1] -UseKit).Count | Should Be 0
        }
    }
    It 'reports plain tables, buttons, fields and dialogs a change adds without a kit class, once per kind' {
        $new = "<table><tr><td>1</td></tr></table>`n<button type=`"button`">Go</button>`n<button>Again</button>`n<input id=`"q`">`n<select id=`"s`"></select>`n<textarea id=`"t`"></textarea>`n<dialog open>Hi</dialog>"
        $r = @(Find-KitBypass 'index.html' '' $new)
        $r.Count | Should Be 6
        ($r -join ' ') | Should Match 'kit-table.*kit-btn.*kit-input.*kit-select.*kit-textarea.*kit-dialog'
        @(Find-KitBypass 'index.html' '' '<button class="kit-btn kit-btn--primary">Go</button><input class="kit-input"><input type="checkbox"><table class="kit-table"></table>').Count | Should Be 0
        @(Find-KitBypass 'src/App.tsx' '' '<button className="kit-tab" onClick={() => go()}>Go</button><Button>Library part</Button>').Count | Should Be 0
        @(Find-KitBypass 'index.html' '<button>Old</button>' "<button>Old</button>`n<p>New text</p>").Count | Should Be 0   # already there
        @(Find-QualityIssues 'index.html' '' '<button>Go</button>').Count | Should Be 0   # only with the kit
    }
    It 'reports plain elements a script writes as markup, but not comparisons or classes put together from variables' {
        $r = @(Find-KitBypass 'js/app.js' '' "list.innerHTML = '<button type=`"button`">Go</button>';`nhost.innerHTML = '<table><tr><td>1</td></tr></table>';")
        $r.Count | Should Be 2
        ($r -join ' ') | Should Match 'kit-btn.*kit-table'
        @(Find-KitBypass 'js/app.js' '' "el.innerHTML = '<button class=`"kit-btn kit-btn--sm`" type=`"button`">Go</button>';").Count | Should Be 0
        @(Find-KitBypass 'js/app.js' '' "for (var i = 0; i<input.length; i++) { if (a > b) go(); }").Count | Should Be 0
        @(Find-KitBypass 'js/app.js' '' "if (n < select.size && m > 2) go();").Count | Should Be 0
        @(Find-KitBypass 'js/app.js' '' "el.innerHTML = '<button class=`"' + cls + '`">Go</button>';").Count | Should Be 0
        @(Find-KitBypass 'js/app.js' '' 'el.innerHTML = `<button class="${cls}">Go</button>`;').Count | Should Be 0
        @(Find-KitBypass 'js/app.js' '' "el.innerHTML = [`n  '<div>',`n  '<select id=`"s`"></select>'`n].join('');").Count | Should Be 1
        @(Find-KitBypass 'styles/kit/kit.js' '' "x.innerHTML = '<button>Go</button>';").Count | Should Be 0
        @(Find-QualityIssues 'index.html' '' '<button>Go</button>' -UseKit) -join ' ' | Should Match 'kit-btn'
    }
    It 'reports fonts, font sizes, shadows and corners written into styles instead of the kit''s tokens' {
        $r = @(Find-UiSlop 'styles/app.css' '' '.title { font-family: "Segoe UI", sans-serif; font-size: 14px; box-shadow: 0 2px 8px var(--x); border-radius: 6px; }' -UseKit) -join ' '
        foreach ($w in 'a font of your own', 'hard-coded font size', 'shadow of your own', 'rounded corners') { $r | Should Match $w }
        @(Find-UiSlop 'styles/app.css' '' '.t { font-family: var(--kit-font); font-size: var(--kit-text-sm); box-shadow: var(--kit-shadow); border-radius: 999px; }' -UseKit).Count | Should Be 0
        @(Find-UiSlop 'styles/app.css' '' '.t { border-radius: 50%; box-shadow: none; border-radius: 0; }' -UseKit).Count | Should Be 0
        @(Find-UiSlop 'styles/app.css' '' '.title { font-family: Georgia; }').Count | Should Be 0   # only with the kit
    }
    It 'reports an emoji used as an icon in a button, heading, label or link' {
        $rocket = [char]::ConvertFromUtf32(0x1F680); $check = [string][char]0x2705
        @(Find-UiSlop 'index.html' '' "<button class=`"kit-btn`">$rocket Launch</button>" -UseKit) -join ' ' | Should Match 'data-kit-icon'
        @(Find-UiSlop 'index.html' '' "<h2>$check Done</h2>") -join ' ' | Should Match 'SVG icon'
        @(Find-UiSlop 'index.html' '' "<p>Today $rocket in the text</p>" -UseKit).Count | Should Be 0
        @(Find-UiSlop 'index.html' '' '<button class="kit-btn">Launch</button>' -UseKit).Count | Should Be 0
    }
    It 'reports a chart library added to a project with the kit''s charts' {
        foreach ($c in @(
            @('index.html', '<script src="https://cdn.example.test/npm/chart.js"></script>'),
            @('src/app.js', 'const c = new Chart(ctx, config);'),
            @('src/App.tsx', 'import { BarChart } from "recharts";'),
            @('src/main.js', "const chart = echarts.init(el);"),
            @('package.json', '    "chart.js": "^4.4.0",'))) {
            @(Find-UiSlop $c[0] '' $c[1] -UseKit) -join ' ' | Should Match 'chart library'
            @(Find-UiSlop $c[0] '' $c[1]).Count | Should Be 0
        }
        @(Find-UiSlop 'src/app.js' '' 'KitCharts.bar(el, data);' -UseKit).Count | Should Be 0
        Mock -ModuleName Guardrails Test-UiKitPart { $Name -ne 'charts' }
        @(Find-UiSlop 'src/app.js' '' 'const c = new Chart(ctx, config);' -UseKit).Count | Should Be 0
    }
}

Describe 'The kit charts' {
    It 'cover every chart type the rule names, with a hidden data table for screen readers' {
        $js = [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\kit-charts.js'))
        foreach ($k in 'bar', 'line', 'area', 'ring', 'gauge', 'heatmap', 'sparkline') { $js | Should Match ("\b" + $k + "\b") }
        $js | Should Match 'kit-chart__table'
        $js | Should Match 'role: "img"'
        [IO.File]::ReadAllText((Join-Path $root 'prompts\rules\uikit.md')) | Should Match 'data-kit-chart="bar\|line\|area\|ring\|gauge\|heatmap\|sparkline\|barlist"'
    }
    It 'stack bars, list categories, show ring values and filter on a click, with the CSS for each' {
        $js = [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\kit-charts.js'))
        foreach ($w in 'data.stacked', 'function barlist', 'data.legend === "values"', '"kit:select"', 'data.selectedSeries', 'function barPath') { $js.Contains($w) | Should Be $true }
        $css = [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\kit.css'))
        foreach ($c in '.kit-barlist__row', '.kit-barlist__fill', '.kit-chart__legend--values', '.kit-chart__bar.is-off', '.kit-chart--ring', '.kit-chips', '.kit-chip', '.kit-panel--sticky', '.kit-grid--charts', '.kit-grid__wide', '.kit-header--band a') { $css.Contains($c) | Should Be $true }
        [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\react\Chart.tsx')) | Should Match 'onSelect'
    }
    It 'colour bar list rows and ring parts by meaning, show shares, draw funnels and lines over bars' {
        $js = [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\kit-charts.js'))
        foreach ($w in 'function tone(', 'ok: "--kit-ok"', 'warn: "--kit-warn"', 'error: "--kit-error"', 'muted: "--kit-text-muted"', 'data.share', 'data.base === "first"', 'Number(data.total)', 'kit-barlist kit-barlist--share', 'tone(it.color', 'sr.type === "line"', 'sr.axis === "right"', 'opts.colors') { $js.Contains($w) | Should Be $true }
        # Only kit tokens: a hard-coded colour in an item falls back to the series colour.
        $js.Contains('/^var\(--kit-[\w-]+\)$/') | Should Be $true
        @($js.ToCharArray() | Where-Object { [int]$_ -gt 127 }).Count | Should Be 0
        $css = [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\kit.css'))
        foreach ($c in '.kit-barlist--share .kit-barlist__row', '.kit-barlist__value b', '.kit-progress--ok .kit-progress__bar', '.kit-progress--warn .kit-progress__bar', '.kit-progress--error .kit-progress__bar', '.kit-figure__bar', '.kit-select.is-active', '.kit-header--band .kit-btn--ghost') { $css.Contains($c) | Should Be $true }
        $css | Should Match '\.kit-panel__title \{ font-size: var\(--kit-text-md\)'
        $ex = [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\kit-examples.html'))
        foreach ($w in '"share":true', '"base":"first"', '"color":"ok"', '"color":"warn"', '"color":"error"', '"type":"line","axis":"right"', 'kit-progress kit-progress--ok kit-figure__bar', 'share: true') { $ex.Contains($w) | Should Be $true }
        [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\react\Chart.tsx')) | Should Match 'base: "first"'
    }
    It 'leave the choice of chart to Copilot and give each choice its kit part and colours by meaning' {
        $rule = [IO.File]::ReadAllText((Join-Path $root 'prompts\rules\uikit.md'))
        $rule | Should Match '- Your choice, the kit''s look: which data to show, and as what, is yours to decide; the kit sets no limits on it'
        $rule | Should Match '\(vertical, horizontal or stacked bars'
        $rule | Should Match '- Dashboards: what a dashboard shows is your choice'
        $rule | Should Match 'bar "horizontal": true'
        $rule | Should Match 'Whatever you choose must look like the kit: draw it with the kit part for that form'
        $rule | Should Not Match 'never a vertical bar chart'
        $rule | Should Match '"base": "first"'
        $rule | Should Match 'a bar series with "type": "line" \(and "axis": "right"'
        $rule | Should Match '"color": "ok", "warn", "error", "muted" or "accent"'
        $rule | Should Match 'kit-progress kit-figure__bar'
    }
    It 'sort and page a table with kit.js, shown in the examples with an empty state' {
        $js = [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\kit.js'))
        foreach ($w in 'function setupTable', 'data-kit-sort', 'data-kit-pages', '"kit:sort"', '"kit:page"', 'data-kit-empty', 'kit-table__sort', 'kit-pager') { $js.Contains($w) | Should Be $true }
        $css = [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\kit.css'))
        foreach ($c in '.kit-table__sort', '.kit-pager', '.kit-pager__info', 'th[aria-sort="ascending"]') { $css.Contains($c) | Should Be $true }
        $ex = [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\kit-examples.html'))
        $ex | Should Match '<table class="kit-table" data-kit-sort data-kit-pages="\d+">'
        $ex | Should Match '<tr data-kit-empty><td colspan="\d+"><div class="kit-empty">'
        $rule = [IO.File]::ReadAllText((Join-Path $root 'prompts\rules\uikit.md'))
        foreach ($w in 'data-kit-sort', 'data-kit-pages', 'Never an emoji as an icon', 'var\(--kit-radius\)', 'empty state') { $rule | Should Match $w }
    }
    It 'leave thousands of rows to the page (data-kit-rows="external") and scroll a long table under its header' {
        $js = [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\kit.js'))
        foreach ($w in 'data-kit-rows', '"external"', 'data-kit-total', 'data-kit-page', 'attributeFilter: ["data-kit-total", "data-kit-page"]', 'key: th.getAttribute("data-key")', 'start: page * size') { $js.Contains($w) | Should Be $true }
        $css = [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\kit.css'))
        $css.Contains('.kit-table-wrap--scroll .kit-table thead th { position: sticky;') | Should Be $true
        $ex = [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\kit-examples.html'))
        $ex | Should Match '(?s)<!-- kit-part:interactive -->.*<section id="long-table">.*<!-- /kit-part:interactive -->'
        $ex | Should Match '<table class="kit-table" id="kit-long" data-kit-sort data-kit-pages="50" data-kit-rows="external">'
        $ex | Should Match 'KitData\.toCsv\(rows'
        $rule = [IO.File]::ReadAllText((Join-Path $root 'prompts\rules\uikit.md'))
        $rule | Should Match 'data-kit-rows="external" and data-key="FIELD"'
        $rule | Should Match 'kit-table-wrap--scroll'
        $rule | Should Match 'KitData\.download\("NAME\.csv", KitData\.toCsv'
    }
    It 'switch light and dark with data-kit-theme, following the computer until clicked' {
        $js = [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\kit.js'))
        foreach ($w in 'function setupTheme', '[data-kit-theme]', 'prefers-color-scheme: dark', '"kit:theme"', 'try { localStorage.setItem', 'try { return localStorage.getItem') { $js.Contains($w) | Should Be $true }
        [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\kit-examples.html')) | Should Match '(?s)<header class="kit-header kit-header--band">.*data-kit-theme.*</header>'
        [IO.File]::ReadAllText((Join-Path $root 'prompts\rules\uikit.md')) | Should Match 'data-kit-theme.*never write your own'
    }
    It 'have a dashboard example with invented data that uses the selectable charts' {
        $ex = [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\kit-examples.html'))
        $ex | Should Match '<header class="kit-header kit-header--band">'
        $ex | Should Match '(?s)<!-- kit-part:charts -->.*<section id="dashboard">.*<!-- /kit-part:charts -->'
        foreach ($w in 'KitCharts.barlist', 'stacked: true', 'legend: "values"', 'kit:select', 'kit-chips', 'kit-panel--sticky', 'kit-grid--charts') { $ex.Contains($w) | Should Be $true }
    }
    It 'keep the classes a page gets from kit-charts.js (bar lists, ring values) in the project''s kit.css' {
        $p = Join-Path $env:TEMP ('ccb-kitc-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        $null = Install-UiKit $p $root
        [IO.File]::WriteAllText((Join-Path $p 'index.html'), '<div class="kit-chart" data-kit-chart="barlist" data-kit-data=''{"items":[]}'' aria-label="Example"></div><script src="styles/kit/kit-charts.js"></script>')
        $u = Update-UiKitProject $p $root
        $u.added -contains 'styles/kit/kit-charts.js' | Should Be $true
        $css = [IO.File]::ReadAllText((Join-Path $p 'styles\kit\kit.css'))
        $css | Should Match '\.kit-barlist__row \{'
        $css | Should Match '\.kit-chart__legend--values'
        $css | Should Match '\.kit-barlist--share \.kit-barlist__row'
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
    }
}

Describe 'What the kit offers, for every task (Format-UiKitContext)' {
    It 'indexes every part of the examples page with its lines, from the comment above it' {
        $ex = [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\kit-examples.html'))
        $idx = @(Get-KitExamplesIndex $ex)
        $idx.Count | Should Be (@([regex]::Matches($ex, '<section\b')).Count + 1)   # every section and the page header
        $lines = $ex.Replace("`r`n", "`n").Split("`n")
        foreach ($s in $idx) {
            $s.end | Should BeGreaterThan $s.start
            ($lines[($s.start - 1)..($s.end - 1)] -join "`n") | Should Match '(<section|<header)'
            $lines[$s.end - 1] | Should Match '</(section|header)>'
        }
        $t = @($idx | Where-Object { $_.id -eq 'table' })[0]
        $lines[$t.start - 1] | Should Match '^<!--'
        foreach ($c in 'kit-table', 'kit-badge', 'kit-pager', 'kit-empty') { @($t.classes) -contains $c | Should Be $true }
        @($idx | Where-Object { $_.title -eq 'Dashboard' }).Count | Should Be 1
        @($idx | ForEach-Object { $_.classes } | Where-Object { $_ -match '^kit-(h2|row|charts|icons|data)$' }).Count | Should Be 0
    }
    It 'tells where the kit is, what each part and script offers, and what the project uses' {
        $p = Join-Path $env:TEMP ('ccb-kitx-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        Format-UiKitContext $p $root | Should BeNullOrEmpty   # no kit yet
        $null = Install-UiKit $p $root
        Test-ReactProject $p | Should Be $false   # the catalogue's own React parts do not count
        $c = Format-UiKitContext $p $root
        $c | Should Match 'build every interface from it first'
        $c | Should Match '\.streamhub/ui-kit/kit-examples\.html has the markup of every part'
        $c | Should Match '(?m)^  Buttons: lines \d+-\d+ \(kit-btn'
        $c | Should Match '(?m)^  Dashboard: lines \d+-\d+'
        $c | Should Match 'kit-charts\.js \(charts on the kit colours: bar \(grouped or stacked\).*barlist'
        $c | Should Match 'kit\.js \(behaviour by data-kit-\* attributes: sortable tables with pages'
        $c | Should Match 'In use: styles/kit/ kit\.css, tokens\.css'
        $c | Should Not Match 'React parts'
        [IO.File]::WriteAllText((Join-Path $p 'package.json'), '{ "dependencies": { "react": "^19.0.0" } }')
        Format-UiKitContext $p $root | Should Match 'React parts \(import from styles/kit/react/NAME\): Chart, .*HoldButton'
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
    }
    It 'sends the kit rule with any change to a web project that has the kit, not only interface requests' {
        $ctx = @{ Paths = @('index.html', 'app.js', 'styles/kit/tokens.css', 'styles/kit/kit.css'); Traits = @('web', 'code') }
        $ids = @(& (Get-Module Prompts) { param($c) Get-PromptModules -Text 'Fix the wrong totals per region' -Context $c } $ctx)
        $ids -contains 'rules:uikit' | Should Be $true
        $ctx.Paths = @('index.html', 'app.js')
        $ids = @(& (Get-Module Prompts) { param($c) Get-PromptModules -Text 'Fix the wrong totals per region' -Context $c } $ctx)
        $ids -contains 'rules:uikit' | Should Be $false
    }
    It 'puts the kit first in the rule and says where everything is' {
        $rule = [IO.File]::ReadAllText((Join-Path $root 'prompts\rules\uikit.md'))
        $rule | Should Match 'The kit comes first, for every piece of interface'
        $rule | Should Match 'Never build your own version of something the kit has'
        $rule | Should Match 'The project context lists its parts with their lines'
    }
}

Describe 'Update-UiKitCatalog' {
    It 'brings a catalogue from an older kit revision up to date, with the unchanged kit files the pages use' {
        $p = Join-Path $env:TEMP ('ccb-kitv-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        $null = Install-UiKit $p $root
        $cat = Join-Path $p '.streamhub\ui-kit'
        Get-KitCatalogRevision $cat | Should BeGreaterThan 1
        @(Update-UiKitCatalog $p $root).Count | Should Be 0   # current: nothing to do
        # An older catalogue: VERSION.txt without a revision, older files, one copy the project changed.
        [IO.File]::WriteAllText((Join-Path $cat 'VERSION.txt'), 'UI kit from StreamHub v0.1.90, copied 2026-01-01.')
        foreach ($f in 'kit-charts.js', 'kit.js') { [IO.File]::WriteAllText((Join-Path $cat $f), "/* old $f */") }
        [IO.File]::WriteAllText((Join-Path $cat 'tokens.css'), ':root { --kit-accent: #224466; }')
        [IO.File]::WriteAllText((Join-Path $p 'styles\kit\kit-charts.js'), '/* old kit-charts.js */')
        [IO.File]::WriteAllText((Join-Path $p 'styles\kit\kit.js'), '/* the project''s own change */')
        Get-KitCatalogRevision $cat | Should Be 1
        @(Update-UiKitCatalog $p $root) -join ',' | Should Be 'styles/kit/kit-charts.js'
        [IO.File]::ReadAllText((Join-Path $cat 'kit-charts.js')) | Should Match 'function barlist'
        [IO.File]::ReadAllText((Join-Path $p 'styles\kit\kit-charts.js')) | Should Match 'function barlist'
        [IO.File]::ReadAllText((Join-Path $p 'styles\kit\kit.js')) | Should Be '/* the project''s own change */'
        [IO.File]::ReadAllText((Join-Path $cat 'tokens.css')) | Should Match '#224466'
        Get-KitCatalogRevision $cat | Should BeGreaterThan 1
        @(Update-UiKitCatalog $p $root).Count | Should Be 0
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
    }
    It 'makes a whole unchanged copy of the old catalogue''s kit.css generated again, and keeps one the project changed' {
        foreach ($own in $false, $true) {
            $p = Join-Path $env:TEMP ('ccb-kitold-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
            $null = Install-UiKit $p $root
            $cat = Join-Path $p '.streamhub\ui-kit'
            [IO.File]::WriteAllText((Join-Path $p 'index.html'), '<body class="kit-page"><div class="kit-panel"><h2 class="kit-panel__title">Totals</h2></div></body>')
            # An older project: the whole old kit.css copied into styles/kit (no Generated line).
            $oldCss = "/*`n  UI kit components (an older revision).`n*/`n.kit-panel__title { font-weight: 600; margin: 0; }`n.kit-old { color: var(--kit-text); }`n"
            [IO.File]::WriteAllText((Join-Path $cat 'kit.css'), $oldCss)
            [IO.File]::WriteAllText((Join-Path $cat 'VERSION.txt'), 'UI kit from StreamHub v0.1.109, copied 2026-10-08.')
            $copy = Join-Path $p 'styles\kit\kit.css'
            [IO.File]::WriteAllText($copy, $(if ($own) { $oldCss + '.mine { margin: 0; }' } else { $oldCss }))
            $r = @(Update-UiKitCatalog $p $root)
            $null = Update-UiKitProject $p $root
            $css = [IO.File]::ReadAllText($copy)
            if ($own) {
                $r -contains 'styles/kit/kit.css' | Should Be $false
                $css | Should Match '\.mine'
            } else {
                $r -contains 'styles/kit/kit.css' | Should Be $true
                $css | Should Match '^/\* Generated by the helper program from the UI kit'
                $css | Should Match '\.kit-panel__title \{ font-size: var\(--kit-text-md\)'
                $css | Should Not Match '\.kit-old'
            }
            Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
        }
    }
    It 'does nothing for a project without a catalogue' {
        $p = Join-Path $env:TEMP ('ccb-kitn-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        @(Update-UiKitCatalog $p $root).Count | Should Be 0
        Test-Path (Join-Path $p '.streamhub') | Should Be $false
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
    }
}

Describe 'The kit files themselves' {
    It 'credit kokonutui where its parts are used, with its licence alongside' {
        [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\LICENSE-kokonutui.txt')) | Should Match 'Copyright \(c\) 2025 kokonutUI'
        foreach ($f in @(Get-ChildItem (Join-Path $root 'templates\ui-kit\react') -Filter *.tsx | Where-Object { $_.Name -notin 'Chart.tsx', 'Icon.tsx' }) + @(Get-Item (Join-Path $root 'templates\ui-kit\kit.js'))) {
            [IO.File]::ReadAllText($f.FullName) | Should Match '(?s)kokonutui.*MIT'
        }
        [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\LICENSE-bklit-ui.txt')) | Should Match 'Copyright \(c\) 2026 uixmat'
        foreach ($f in 'kit-charts.js', 'react\Chart.tsx') { [IO.File]::ReadAllText((Join-Path $root "templates\ui-kit\$f")) | Should Match '(?s)bklit-ui.*MIT' }
        [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\react\Icon.tsx')) | Should Match 'Lucide icon \(ISC'
    }
    It 'pass the file checks' {
        foreach ($f in 'tokens.css', 'kit.css', 'kit.js', 'kit-examples.html', 'kit-charts.js', 'react\Chart.tsx', 'react\HoldButton.tsx', 'react\SearchBox.tsx', 'react\DropZone.tsx', 'react\Tabs.tsx', 'react\Loading.tsx', 'react\Composer.tsx', 'react\CommandButton.tsx') {
            $path = Join-Path $root "templates\ui-kit\$f"
            @(Test-FileContent $path ([IO.File]::ReadAllText($path))) | Should BeNullOrEmpty
        }
    }
}

Describe 'UI kit parts switched off (Settings > UI kit)' {
    It 'leaves out the files and example sections of parts that are off' {
        Mock -ModuleName UiKit Test-UiKitPart { $Name -ne 'charts' }
        $p = Join-Path $env:TEMP ('ccb-kitp-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        [IO.File]::WriteAllText((Join-Path $p 'package.json'), '{ "dependencies": { "react": "^19.0.0" } }')
        $null = Install-UiKit $p $root
        $cat = Join-Path $p '.streamhub\ui-kit'
        Test-Path (Join-Path $cat 'kit-charts.js') | Should Be $false
        Test-Path (Join-Path $cat 'react\Chart.tsx') | Should Be $false
        Test-Path (Join-Path $cat 'kit.js') | Should Be $true
        Test-Path (Join-Path $cat 'react\HoldButton.tsx') | Should Be $true
        # A page that loads the charts anyway gets nothing: the part is off.
        [IO.File]::WriteAllText((Join-Path $p 'index.html'), '<script src="styles/kit/kit-charts.js"></script>')
        @((Update-UiKitProject $p $root).added) -contains 'styles/kit/kit-charts.js' | Should Be $false
        $ex = [IO.File]::ReadAllText((Join-Path $cat 'kit-examples.html'))
        $ex | Should Not Match 'kit-charts\.js'
        $ex | Should Not Match 'data-kit-chart='
        $ex | Should Match 'data-kit-hold'
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
    }
    It 'adds the file readers and pdf.js only while they are on (pdf.js only with the readers)' {
        Mock -ModuleName UiKit Test-UiKitPart { $Name -ne 'pdf' }
        $p = Join-Path $env:TEMP ('ccb-kitd-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        [IO.File]::WriteAllText((Join-Path $p 'package.json'), '{ "dependencies": { "react": "^19.0.0" } }')
        $null = Install-UiKit $p $root
        $cat = Join-Path $p '.streamhub\ui-kit'
        Test-Path (Join-Path $cat 'kit-data.js') | Should Be $true
        Test-Path (Join-Path $cat 'react\useFileData.ts') | Should Be $true
        Test-Path (Join-Path $cat 'vendor') | Should Be $false
        $ex = [IO.File]::ReadAllText((Join-Path $cat 'kit-examples.html'))
        $ex | Should Match 'KitData\.readFile'
        $ex | Should Not Match 'pdf\.min\.js|or PDF'
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
        Mock -ModuleName UiKit Test-UiKitPart { $Name -ne 'data' }
        @(Get-UiKitParts $root) -contains 'pdf' | Should Be $false
    }
    It 'tells Copilot about the file readers by part' {
        Mock -ModuleName Prompts Test-UiKitPart { $Name -ne 'pdf' }
        $t = & (Get-Module Prompts) { param($r) Get-PromptPart $r 'rules:uikit' } $root
        $t | Should Match 'KitData\.readFile'
        $t | Should Match 'pdf\.js is switched off'
        $t | Should Not Match 'pdf\.worker'
        Mock -ModuleName Prompts Test-UiKitPart { $Name -ne 'data' }
        $t = & (Get-Module Prompts) { param($r) Get-PromptPart $r 'rules:uikit' } $root
        $t | Should Not Match 'KitData'
    }
    It 'adds no React files when React versions are off' {
        Mock -ModuleName UiKit Test-UiKitPart { $Name -ne 'react' }
        $p = Join-Path $env:TEMP ('ccb-kitq-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        [IO.File]::WriteAllText((Join-Path $p 'package.json'), '{ "dependencies": { "react": "^19.0.0" } }')
        $null = Install-UiKit $p $root
        Test-Path (Join-Path $p '.streamhub\ui-kit\react') | Should Be $false
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
    }
    It 'leaves out the dashboard line without the charts, and lets a chart library take the kit''s colours' {
        Mock -ModuleName Prompts Test-UiKitPart { $Name -ne 'charts' }
        $t = & (Get-Module Prompts) { param($r) Get-PromptPart $r 'rules:uikit' } $root
        $t | Should Not Match 'Charts:|Dashboards:|Your choice, the kit'
        $t | Should Match 'A chart library gets these colours too'
        $t | Should Match 'kit-header--band'
    }
    It 'tells Copilot only about the parts that are on' {
        Mock -ModuleName Prompts Test-UiKitPart { $Name -notin 'interactive', 'react' }
        $t = & (Get-Module Prompts) { param($r) Get-PromptPart $r 'rules:uikit' } $root
        $t | Should Not Match 'Interactive parts'
        $t | Should Not Match 'styles/kit/react'
        $t | Should Not Match 'data-kit-theme'
        $t | Should Match 'Charts:'
        $t | Should Match 'Your choice, the kit'
    }
    It 'leaves out the export line without the file readers' {
        Mock -ModuleName Prompts Test-UiKitPart { $Name -ne 'data' }
        $t = & (Get-Module Prompts) { param($r) Get-PromptPart $r 'rules:uikit' } $root
        $t | Should Not Match 'Export:|KitData'
        $t | Should Match 'data-kit-theme'
    }
    It 'sends the design rules only while they are on' {
        Mock -ModuleName Prompts Test-UiKitPart { $Name -ne 'designRules' }
        $ids = @(& (Get-Module Prompts) { Get-PromptModules -Text 'Build a dashboard page with a table' -Context @{ Paths = @('index.html'); Traits = @('web', 'code') } })
        $ids -contains 'rules:design' | Should Be $false
        $ids -contains 'rules:ui' | Should Be $true
    }
    It 'skips the generated-look warnings while they are off' {
        Mock -ModuleName Guardrails Test-UiKitPart { $false }
        @(Find-UiSlop 'styles/app.css' '' '.t { background-clip: text; }') | Should BeNullOrEmpty
    }
}

Describe 'UI kit colours (Settings > UI kit > Colours)' {
    It 'gives a project the neutral tokens, without the palette section, when Neutral is chosen' {
        Mock -ModuleName UiKit Get-UiKitColors { 'neutral' }
        $p = Join-Path $env:TEMP ('ccb-kitn-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        $null = Install-UiKit $p $root
        $t = [IO.File]::ReadAllText((Join-Path $p 'styles\kit\tokens.css'))
        $t | Should Match 'neutral colours'
        $t | Should Not Match '--kit-palette-'
        [IO.File]::ReadAllText((Join-Path $p '.streamhub\ui-kit\kit-examples.html')) | Should Not Match 'kit-swatch'
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
    }
    It 'sets no colours with None: neutral starting values that say they are free, and Copilot is told so' {
        Mock -ModuleName UiKit Get-UiKitColors { 'none' }
        $p = Join-Path $env:TEMP ('ccb-kitx-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        $null = Install-UiKit $p $root
        $t = [IO.File]::ReadAllText((Join-Path $p 'styles\kit\tokens.css'))
        $t | Should Match 'no colours set \(Settings > UI kit > Colours: None\)'
        $t | Should Match '--kit-accent:'
        $t | Should Not Match '--kit-palette-'
        [IO.File]::ReadAllText((Join-Path $p '.streamhub\ui-kit\kit-examples.html')) | Should Not Match 'kit-swatch'
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
        Mock -ModuleName Prompts Get-UiKitColors { 'none' }
        $r = & (Get-Module Prompts) { param($a) Get-PromptPart $a 'rules:uikit' } $root
        $r | Should Match 'no colours are set for this project'
        $r | Should Match 'Hard-coded colours and gradients are fine'
        $r | Should Not Match 'do not hard-code colours|--kit-palette|The only gradient|Anything a page draws itself'
        $r | Should Match 'do not hard-code sizes or shadows'
        $r | Should Match 'WCAG AA'
    }
    It 'gives the blue palette by default' {
        Mock -ModuleName UiKit Get-UiKitColors { 'blue' }
        $p = Join-Path $env:TEMP ('ccb-kitb-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        $null = Install-UiKit $p $root
        [IO.File]::ReadAllText((Join-Path $p 'styles\kit\tokens.css')) | Should Match '--kit-palette-blue: #10069f'
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
    }
    It 'keeps both colour files readable (WCAG AA in light and dark), and neither says brand' {
        Import-Module (Join-Path $root 'lib\Contrast.psm1') -Force
        foreach ($f in 'tokens.css', 'tokens-neutral.css') {
            $css = [IO.File]::ReadAllText((Join-Path $root "templates\ui-kit\$f"))
            @(Test-TokenContrast $css) | Should BeNullOrEmpty
            $css | Should Not Match '(?i)brand'
        }
        foreach ($f in 'kit.css', 'kit-examples.html') { [IO.File]::ReadAllText((Join-Path $root "templates\ui-kit\$f")) | Should Not Match '(?i)brand' }
    }
}

Describe 'UI kit icons (Lucide)' {
    It 'ships the whole Lucide set with its licence' {
        $l = & (Get-Module UiKit) { param($r) Get-LucideIcons $r } $root
        $l.icons.Count | Should BeGreaterThan 1500
        $l.icons['check'] | Should Match '<path'
        $l.icons.ContainsKey('trash-2') | Should Be $true      # older names (aliases) work too
        [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\LICENSE-lucide.txt')) | Should Match 'ISC License'
    }
    It 'gives a project the common icons, adds the ones its pages use, and names close ones for a wrong name' {
        $p = Join-Path $env:TEMP ('ccb-kiti-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        $null = Install-UiKit $p $root
        $file = Join-Path $p 'styles\kit\kit-icons.js'
        Test-Path $file | Should Be $false   # no page uses an icon yet
        [IO.File]::WriteAllText((Join-Path $p 'index.html'), '<span data-kit-icon="rocket"></span><span data-kit-icon="calender-plus"></span>')
        $r = Update-UiKitProject $p $root
        $r.added -contains 'styles/kit/kit-icons.js' | Should Be $true
        $r.added -contains 'styles/kit/LICENSE-lucide.txt' | Should Be $true
        [IO.File]::ReadAllText($file) | Should Match '"settings":'
        [IO.File]::ReadAllText($file) | Should Match '"rocket":'
        @($r.unknown).Count | Should Be 1
        @($r.unknown)[0].like[0] | Should Be 'calendar-plus'
        (Update-KitIcons $p $root).written | Should Be $false   # nothing new: the file stays as it is
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
    }
    It 'adds no icons while the Icons part is off' {
        Mock -ModuleName UiKit Test-UiKitPart { $Name -ne 'icons' }
        $p = Join-Path $env:TEMP ('ccb-kitj-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        $null = Install-UiKit $p $root
        [IO.File]::WriteAllText((Join-Path $p 'index.html'), '<span data-kit-icon="rocket"></span>')
        @((Update-UiKitProject $p $root).added) | Where-Object { $_ -match 'icon|lucide' } | Should BeNullOrEmpty
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
    }
}
