# The UI kit (templates/ui-kit, lib/UiKit.psm1): a catalogue in the project's .streamhub/ui-kit/ for
# interface work (setting uiKit), and in styles/kit/ only what the pages use; its rule goes to Copilot with the UI rules; generated-looking patterns
# are reported (Guardrails Find-UiSlop). Made-up project content.
$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Import-Module (Join-Path $root 'lib\Config.psm1') -Force
Import-Module (Join-Path $root 'lib\UiKit.psm1') -Force
Import-Module (Join-Path $root 'lib\Guardrails.psm1') -Force
Import-Module (Join-Path $root 'lib\Prompts.psm1') -Force
Import-Module (Join-Path $root 'lib\Lint.psm1') -Force

Describe 'Install-UiKit' {
    $p = Join-Path $env:TEMP ('ccb-kit-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
    It 'puts the whole kit in the catalogue and only the tokens and the stylesheet in styles/kit, never overwriting the project''s tokens' {
        @(Install-UiKit $p $root) -join ',' | Should Be 'styles/kit/tokens.css,styles/kit/kit.css'
        foreach ($f in 'kit.css', 'kit.js', 'kit-charts.js', 'kit-data.js', 'kit-examples.html', 'LICENSE-kokonutui.txt', 'vendor\pdfjs\pdf.min.js', 'VERSION.txt') {
            Test-Path (Join-Path $p ".streamhub\ui-kit\$f") | Should Be $true
        }
        @(Get-ChildItem (Join-Path $p 'styles\kit') -Recurse -File).Count | Should Be 2
        (Get-Content (Join-Path $p 'styles\kit\kit.css') -TotalCount 1) | Should Match '^/\* Generated by the helper program from the UI kit'
        Test-UiKitInProject $p | Should Be $true
        [IO.File]::WriteAllText((Join-Path $p 'styles\kit\tokens.css'), ':root { --kit-accent: #224466; }')
        @(Install-UiKit $p $root).Count | Should Be 0
        [IO.File]::ReadAllText((Join-Path $p 'styles\kit\tokens.css')) | Should Match '#224466'
    }
    It 'adds a React part when the code imports it, with the script and licence it needs' {
        $r = Join-Path $env:TEMP ('ccb-kitr-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory (Join-Path $r 'src') -Force | Out-Null
        [IO.File]::WriteAllText((Join-Path $r 'package.json'), '{ "dependencies": { "react": "^19.0.0" } }')
        $null = Install-UiKit $r $root
        Test-Path (Join-Path $r '.streamhub\ui-kit\react\HoldButton.tsx') | Should Be $true
        Test-Path (Join-Path $r 'styles\kit\react') | Should Be $false
        [IO.File]::WriteAllText((Join-Path $r 'src\App.tsx'), "import { Chart } from `"../styles/kit/react/Chart`";`nimport { HoldButton } from `"../styles/kit/react/HoldButton`";")
        $u = Update-UiKitProject $r $root
        foreach ($f in 'react/Chart.tsx', 'kit-charts.js', 'LICENSE-bklit-ui.txt', 'react/HoldButton.tsx', 'LICENSE-kokonutui.txt') { $u.added -contains "styles/kit/$f" | Should Be $true }
        $u.added -contains 'styles/kit/kit.js' | Should Be $false
        $css = [IO.File]::ReadAllText((Join-Path $r 'styles\kit\kit.css'))
        $css | Should Match '\.kit-btn--hold\.is-holding::before'
        $css | Should Match '\.kit-chart__bar'
        Remove-Item $r -Recurse -Force -ErrorAction SilentlyContinue
    }
    Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
}

Describe 'Taking what the pages use from the catalogue' {
    $p = Join-Path $env:TEMP ('ccb-kitu-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
    $null = Install-UiKit $p $root
    $css = { [IO.File]::ReadAllText((Join-Path $p 'styles\kit\kit.css')) }
    It 'writes only the rules of the kit classes in use' {
        [IO.File]::WriteAllText((Join-Path $p 'index.html'), '<body class="kit-page"><div class="kit-split"><button class="kit-btn kit-btn--primary">Go</button></div></body>')
        $u = Update-UiKitProject $p $root
        $u.updated -contains 'styles/kit/kit.css' | Should Be $true
        $c = & $css
        $c | Should Match '\.kit-btn--primary \{'
        $c | Should Match '@media \(max-width: 860px\) \{ \.kit-split'
        $c | Should Not Match 'kit-search|kit-chart|kokonutui'
        @((Update-UiKitProject $p $root).updated).Count | Should Be 0   # nothing new: left as it is
    }
    It 'adds a kit script a page loads, with its licence, and the classes the script uses' {
        [IO.File]::WriteAllText((Join-Path $p 'search.html'), '<div class="kit-search" data-kit-search><input class="kit-input"></div><script src="styles/kit/kit.js"></script>')
        $u = Update-UiKitProject $p $root
        $u.added -contains 'styles/kit/kit.js' | Should Be $true
        $u.added -contains 'styles/kit/LICENSE-kokonutui.txt' | Should Be $true
        $c = & $css
        $c | Should Match '\.kit-search__list'
        $c | Should Match 'adapted from kokonutui'
    }
    It 'takes classes made in code by prefix, and leaves pdf.js out until a page loads it' {
        [IO.File]::WriteAllText((Join-Path $p 'badge.js'), 'el.className = "kit-badge kit-badge--" + tone;')
        $null = Update-UiKitProject $p $root
        & $css | Should Match '\.kit-badge--ok'
        Test-Path (Join-Path $p 'styles\kit\vendor') | Should Be $false
        [IO.File]::WriteAllText((Join-Path $p 'read.html'), '<script src="styles/kit/vendor/pdfjs/pdf.min.js"></script><script src="styles/kit/vendor/pdfjs/pdf.worker.min.js"></script><script src="styles/kit/kit-data.js"></script>')
        $u = Update-UiKitProject $p $root
        foreach ($f in 'vendor/pdfjs/pdf.min.js', 'vendor/pdfjs/pdf.worker.min.js', 'vendor/pdfjs/LICENSE-pdfjs.txt', 'kit-data.js') { $u.added -contains "styles/kit/$f" | Should Be $true }
    }
    It 'leaves a kit.css the project made itself alone' {
        [IO.File]::WriteAllText((Join-Path $p 'styles\kit\kit.css'), '.kit-btn { color: red; }')
        $null = Update-UiKitProject $p $root
        & $css | Should Be '.kit-btn { color: red; }'
    }
    It 'refuses a change by Copilot to the generated stylesheet' {
        Import-Module (Join-Path $root 'lib\Executor.psm1')
        Remove-Item (Join-Path $p 'styles\kit\kit.css')
        $null = Update-UiKitProject $p $root
        { Assert-Writable $p 'styles/kit/kit.css' } | Should Throw 'written by the helper program'
        { Assert-Writable $p 'styles/kit/tokens.css' } | Should Not Throw
    }
    Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
}

Describe 'Searching the kit catalogue' {
    It 'lets glob and grep find the catalogue, but not the rest of .streamhub or pdf.js' {
        Import-Module (Join-Path $root 'lib\Executor.psm1')
        $p = Join-Path $env:TEMP ('ccb-kits-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        $null = Install-UiKit $p $root
        [IO.File]::WriteAllText((Join-Path $p '.streamhub\issues.json'), '{ "note": "kit-search__list" }')
        Invoke-GlobAction $p '**/kit-examples.html' | Should Match '^\.streamhub/ui-kit/kit-examples\.html'
        Invoke-GlobAction $p '**/issues.json' | Should Match 'no files match'
        $g = Invoke-GrepAction $p 'kit-search__list'
        $g | Should Match '\.streamhub/ui-kit/kit-examples\.html:\d+:'
        $g | Should Match '\.streamhub/ui-kit/kit\.css:\d+:'
        $g | Should Not Match 'issues\.json'
        Invoke-GrepAction $p 'getDocument' | Should Not Match 'vendor/pdfjs'
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
    }
}

Describe 'Select-KitCss' {
    It 'keeps the used selectors of a list, used @media rules, named keyframes and a licence note once' {
        $src = "/* header */`n.kit-a { x: 1; }`n/* Parts adapted from X (MIT licence, see LICENSE-x.txt). */`n.kit-b, .kit-c:hover { y: 2; }`n@media (max-width: 9px) { .kit-b { z: 3; } .kit-d { z: 4; } }`n.kit-e .kit-b { w: 5; }`n@keyframes kit-spin { to { a: b; } }`n.kit-b { animation: kit-spin 1s; }"
        $used = New-Object 'System.Collections.Generic.HashSet[string]'; [void]$used.Add('kit-b')
        $out = Select-KitCss $src @{ classes = $used; prefixes = @() }
        $out | Should Not Match 'header|kit-a|kit-c|kit-d|kit-e'
        $out | Should Match '(?m)^\.kit-b \{ y: 2; \}'
        $out | Should Match '@media \(max-width: 9px\) \{ \.kit-b \{ z: 3; \} \}'
        $out | Should Match '@keyframes kit-spin'
        ([regex]::Matches($out, 'MIT licence')).Count | Should Be 1
    }
}

Describe 'The UI kit rule' {
    It 'goes with the UI rules while the setting is on' {
        $ids = @(& (Get-Module Prompts) { Get-PromptModules -Text 'Build a dashboard page with a table and filters' -Context @{ Paths = @('index.html'); Traits = @('web', 'code') } })
        $ids -contains 'rules:ui' | Should Be $true
        $ids -contains 'rules:uikit' | Should Be $true
    }
    It 'is left out when the setting is off' {
        Mock -ModuleName Prompts Test-UiKitOn { $false }
        $ids = @(& (Get-Module Prompts) { Get-PromptModules -Text 'Build a dashboard page with a table and filters' -Context @{ Paths = @('index.html'); Traits = @('web', 'code') } })
        $ids -contains 'rules:uikit' | Should Be $false
    }
    It 'names only classes the kit has' {
        $rule = [IO.File]::ReadAllText((Join-Path $root 'prompts\rules\uikit.md'))
        $css = [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\kit.css'))
        $line = (@($rule.Split("`n") | Where-Object { $_ -like '- Components:*' -or $_ -like '- Interactive parts*' }) -join ' ')
        foreach ($m in [regex]::Matches($line, '(?<![\w-])kit-[a-z0-9_-]+')) { $css | Should Match ([regex]::Escape('.' + $m.Value.TrimEnd('-'))) }
    }
}

Describe 'Find-UiSlop' {
    It 'reports gradient text, thick side stripes and decorative blur that a change adds' {
        $new = ".title { background: linear-gradient(90deg, red, blue); background-clip: text; }`n.note { border-left: 4px solid #c00; }`n.glass { backdrop-filter: blur(12px); }"
        $r = @(Find-UiSlop 'styles/app.css' '' $new)
        $r.Count | Should Be 3
        ($r -join ' ') | Should Match 'gradient text'
        ($r -join ' ') | Should Match 'side stripe'
        ($r -join ' ') | Should Match 'blur'
    }
    It 'reports hard-coded colours only with the kit in the project, and not in the tokens file' {
        $new = '.box { color: #333; }'
        @(Find-UiSlop 'styles/app.css' '' $new).Count | Should Be 0
        @(Find-UiSlop 'styles/app.css' '' $new -UseKit) -join ' ' | Should Match 'hard-coded colour'
        @(Find-UiSlop 'styles/kit/tokens.css' '' ':root { --kit-accent: #10069f; }' -UseKit).Count | Should Be 0
        @(Find-UiSlop 'styles/app.css' '' '.box { color: var(--kit-text); border: 1px solid var(--kit-border); }' -UseKit).Count | Should Be 0
    }
    It 'leaves lines the file already had alone' {
        $old = '.note { border-left: 4px solid #c00; }'
        @(Find-UiSlop 'styles/app.css' $old "$old`n.x { margin: 0; }").Count | Should Be 0
    }
}

Describe 'The kit charts' {
    It 'cover every chart type the rule names, with a hidden data table for screen readers' {
        $js = [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\kit-charts.js'))
        foreach ($k in 'bar', 'line', 'area', 'ring', 'gauge', 'heatmap', 'sparkline') { $js | Should Match ("\b" + $k + "\b") }
        $js | Should Match 'kit-chart__table'
        $js | Should Match 'role: "img"'
        [IO.File]::ReadAllText((Join-Path $root 'prompts\rules\uikit.md')) | Should Match 'data-kit-chart="bar\|line\|area\|ring\|gauge\|heatmap\|sparkline"'
    }
}

Describe 'The kit files themselves' {
    It 'credit kokonutui where its parts are used, with its licence alongside' {
        [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\LICENSE-kokonutui.txt')) | Should Match 'Copyright \(c\) 2025 kokonutUI'
        foreach ($f in @(Get-ChildItem (Join-Path $root 'templates\ui-kit\react') -Filter *.tsx | Where-Object { $_.Name -notin 'Chart.tsx', 'Icon.tsx' }) + @(Get-Item (Join-Path $root 'templates\ui-kit\kit.js'))) {
            [IO.File]::ReadAllText($f.FullName) | Should Match '(?s)kokonutui.*MIT'
        }
        [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\LICENSE-bklit-ui.txt')) | Should Match 'Copyright \(c\) 2026 uixmat'
        foreach ($f in 'kit-charts.js', 'react\Chart.tsx') { [IO.File]::ReadAllText((Join-Path $root "templates\ui-kit\$f")) | Should Match '(?s)bklit-ui.*MIT' }
        [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\react\Icon.tsx')) | Should Match 'Lucide icon \(ISC'
    }
    It 'pass the file checks' {
        foreach ($f in 'tokens.css', 'kit.css', 'kit.js', 'kit-examples.html', 'kit-charts.js', 'react\Chart.tsx', 'react\HoldButton.tsx', 'react\SearchBox.tsx', 'react\DropZone.tsx', 'react\Tabs.tsx', 'react\Loading.tsx', 'react\Composer.tsx', 'react\CommandButton.tsx') {
            $path = Join-Path $root "templates\ui-kit\$f"
            @(Test-FileContent $path ([IO.File]::ReadAllText($path))) | Should BeNullOrEmpty
        }
    }
}

Describe 'UI kit parts switched off (Settings > UI kit)' {
    It 'leaves out the files and example sections of parts that are off' {
        Mock -ModuleName UiKit Test-UiKitPart { $Name -ne 'charts' }
        $p = Join-Path $env:TEMP ('ccb-kitp-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        [IO.File]::WriteAllText((Join-Path $p 'package.json'), '{ "dependencies": { "react": "^19.0.0" } }')
        $null = Install-UiKit $p $root
        $cat = Join-Path $p '.streamhub\ui-kit'
        Test-Path (Join-Path $cat 'kit-charts.js') | Should Be $false
        Test-Path (Join-Path $cat 'react\Chart.tsx') | Should Be $false
        Test-Path (Join-Path $cat 'kit.js') | Should Be $true
        Test-Path (Join-Path $cat 'react\HoldButton.tsx') | Should Be $true
        # A page that loads the charts anyway gets nothing: the part is off.
        [IO.File]::WriteAllText((Join-Path $p 'index.html'), '<script src="styles/kit/kit-charts.js"></script>')
        @((Update-UiKitProject $p $root).added) -contains 'styles/kit/kit-charts.js' | Should Be $false
        $ex = [IO.File]::ReadAllText((Join-Path $cat 'kit-examples.html'))
        $ex | Should Not Match 'kit-charts\.js'
        $ex | Should Not Match 'data-kit-chart='
        $ex | Should Match 'data-kit-hold'
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
    }
    It 'adds the file readers and pdf.js only while they are on (pdf.js only with the readers)' {
        Mock -ModuleName UiKit Test-UiKitPart { $Name -ne 'pdf' }
        $p = Join-Path $env:TEMP ('ccb-kitd-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        [IO.File]::WriteAllText((Join-Path $p 'package.json'), '{ "dependencies": { "react": "^19.0.0" } }')
        $null = Install-UiKit $p $root
        $cat = Join-Path $p '.streamhub\ui-kit'
        Test-Path (Join-Path $cat 'kit-data.js') | Should Be $true
        Test-Path (Join-Path $cat 'react\useFileData.ts') | Should Be $true
        Test-Path (Join-Path $cat 'vendor') | Should Be $false
        $ex = [IO.File]::ReadAllText((Join-Path $cat 'kit-examples.html'))
        $ex | Should Match 'KitData\.readFile'
        $ex | Should Not Match 'pdf\.min\.js|or PDF'
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
        Mock -ModuleName UiKit Test-UiKitPart { $Name -ne 'data' }
        @(Get-UiKitParts $root) -contains 'pdf' | Should Be $false
    }
    It 'tells Copilot about the file readers by part' {
        Mock -ModuleName Prompts Test-UiKitPart { $Name -ne 'pdf' }
        $t = & (Get-Module Prompts) { param($r) Get-PromptPart $r 'rules:uikit' } $root
        $t | Should Match 'KitData\.readFile'
        $t | Should Match 'pdf\.js is switched off'
        $t | Should Not Match 'pdf\.worker'
        Mock -ModuleName Prompts Test-UiKitPart { $Name -ne 'data' }
        $t = & (Get-Module Prompts) { param($r) Get-PromptPart $r 'rules:uikit' } $root
        $t | Should Not Match 'KitData'
    }
    It 'adds no React files when React versions are off' {
        Mock -ModuleName UiKit Test-UiKitPart { $Name -ne 'react' }
        $p = Join-Path $env:TEMP ('ccb-kitq-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        [IO.File]::WriteAllText((Join-Path $p 'package.json'), '{ "dependencies": { "react": "^19.0.0" } }')
        $null = Install-UiKit $p $root
        Test-Path (Join-Path $p '.streamhub\ui-kit\react') | Should Be $false
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
    }
    It 'tells Copilot only about the parts that are on' {
        Mock -ModuleName Prompts Test-UiKitPart { $Name -notin 'interactive', 'react' }
        $t = & (Get-Module Prompts) { param($r) Get-PromptPart $r 'rules:uikit' } $root
        $t | Should Not Match 'Interactive parts'
        $t | Should Not Match 'styles/kit/react'
        $t | Should Match 'Charts:'
    }
    It 'sends the design rules only while they are on' {
        Mock -ModuleName Prompts Test-UiKitPart { $Name -ne 'designRules' }
        $ids = @(& (Get-Module Prompts) { Get-PromptModules -Text 'Build a dashboard page with a table' -Context @{ Paths = @('index.html'); Traits = @('web', 'code') } })
        $ids -contains 'rules:design' | Should Be $false
        $ids -contains 'rules:ui' | Should Be $true
    }
    It 'skips the generated-look warnings while they are off' {
        Mock -ModuleName Guardrails Test-UiKitPart { $false }
        @(Find-UiSlop 'styles/app.css' '' '.t { background-clip: text; }') | Should BeNullOrEmpty
    }
}

Describe 'UI kit colours (Settings > UI kit > Colours)' {
    It 'gives a project the neutral tokens, without the palette section, when Neutral is chosen' {
        Mock -ModuleName UiKit Get-UiKitColors { 'neutral' }
        $p = Join-Path $env:TEMP ('ccb-kitn-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        $null = Install-UiKit $p $root
        $t = [IO.File]::ReadAllText((Join-Path $p 'styles\kit\tokens.css'))
        $t | Should Match 'neutral colours'
        $t | Should Not Match '--kit-palette-'
        [IO.File]::ReadAllText((Join-Path $p '.streamhub\ui-kit\kit-examples.html')) | Should Not Match 'kit-swatch'
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
    }
    It 'sets no colours with None: neutral starting values that say they are free, and Copilot is told so' {
        Mock -ModuleName UiKit Get-UiKitColors { 'none' }
        $p = Join-Path $env:TEMP ('ccb-kitx-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        $null = Install-UiKit $p $root
        $t = [IO.File]::ReadAllText((Join-Path $p 'styles\kit\tokens.css'))
        $t | Should Match 'no colours set \(Settings > UI kit > Colours: None\)'
        $t | Should Match '--kit-accent:'
        $t | Should Not Match '--kit-palette-'
        [IO.File]::ReadAllText((Join-Path $p '.streamhub\ui-kit\kit-examples.html')) | Should Not Match 'kit-swatch'
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
        Mock -ModuleName Prompts Get-UiKitColors { 'none' }
        $r = & (Get-Module Prompts) { param($a) Get-PromptPart $a 'rules:uikit' } $root
        $r | Should Match 'no colours are set for this project'
        $r | Should Match 'Hard-coded colours and gradients are fine'
        $r | Should Not Match 'do not hard-code colours|--kit-palette|The only gradient'
        $r | Should Match 'do not hard-code sizes or shadows'
        $r | Should Match 'WCAG AA'
    }
    It 'gives the blue palette by default' {
        Mock -ModuleName UiKit Get-UiKitColors { 'blue' }
        $p = Join-Path $env:TEMP ('ccb-kitb-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        $null = Install-UiKit $p $root
        [IO.File]::ReadAllText((Join-Path $p 'styles\kit\tokens.css')) | Should Match '--kit-palette-blue: #10069f'
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
    }
    It 'keeps both colour files readable (WCAG AA in light and dark), and neither says brand' {
        Import-Module (Join-Path $root 'lib\Contrast.psm1') -Force
        foreach ($f in 'tokens.css', 'tokens-neutral.css') {
            $css = [IO.File]::ReadAllText((Join-Path $root "templates\ui-kit\$f"))
            @(Test-TokenContrast $css) | Should BeNullOrEmpty
            $css | Should Not Match '(?i)brand'
        }
        foreach ($f in 'kit.css', 'kit-examples.html') { [IO.File]::ReadAllText((Join-Path $root "templates\ui-kit\$f")) | Should Not Match '(?i)brand' }
    }
}

Describe 'UI kit icons (Lucide)' {
    It 'ships the whole Lucide set with its licence' {
        $l = & (Get-Module UiKit) { param($r) Get-LucideIcons $r } $root
        $l.icons.Count | Should BeGreaterThan 1500
        $l.icons['check'] | Should Match '<path'
        $l.icons.ContainsKey('trash-2') | Should Be $true      # older names (aliases) work too
        [IO.File]::ReadAllText((Join-Path $root 'templates\ui-kit\LICENSE-lucide.txt')) | Should Match 'ISC License'
    }
    It 'gives a project the common icons, adds the ones its pages use, and names close ones for a wrong name' {
        $p = Join-Path $env:TEMP ('ccb-kiti-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        $null = Install-UiKit $p $root
        $file = Join-Path $p 'styles\kit\kit-icons.js'
        Test-Path $file | Should Be $false   # no page uses an icon yet
        [IO.File]::WriteAllText((Join-Path $p 'index.html'), '<span data-kit-icon="rocket"></span><span data-kit-icon="calender-plus"></span>')
        $r = Update-UiKitProject $p $root
        $r.added -contains 'styles/kit/kit-icons.js' | Should Be $true
        $r.added -contains 'styles/kit/LICENSE-lucide.txt' | Should Be $true
        [IO.File]::ReadAllText($file) | Should Match '"settings":'
        [IO.File]::ReadAllText($file) | Should Match '"rocket":'
        @($r.unknown).Count | Should Be 1
        @($r.unknown)[0].like[0] | Should Be 'calendar-plus'
        (Update-KitIcons $p $root).written | Should Be $false   # nothing new: the file stays as it is
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
    }
    It 'adds no icons while the Icons part is off' {
        Mock -ModuleName UiKit Test-UiKitPart { $Name -ne 'icons' }
        $p = Join-Path $env:TEMP ('ccb-kitj-' + [guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $p | Out-Null
        $null = Install-UiKit $p $root
        [IO.File]::WriteAllText((Join-Path $p 'index.html'), '<span data-kit-icon="rocket"></span>')
        @((Update-UiKitProject $p $root).added) | Where-Object { $_ -match 'icon|lucide' } | Should BeNullOrEmpty
        Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue
    }
}
