# The UI kit (templates/ui-kit): colour and size tokens, components and an examples page, added to a
# project the first time Copilot builds an interface there (setting uiKit). Copied, not linked: the
# files are then the project's own, and nothing in them is overwritten later.

Import-Module (Join-Path $PSScriptRoot 'Config.psm1')

# The files of each part (Settings > UI kit). The base is always there with the kit.
$script:KitParts = [ordered]@{
    base        = @('tokens.css', 'kit.css', 'kit-examples.html')
    interactive = @('kit.js', 'LICENSE-kokonutui.txt')
    charts      = @('kit-charts.js', 'LICENSE-bklit-ui.txt')
    icons       = @('LICENSE-lucide.txt')       # kit-icons.js is written by Update-KitIcons
    data        = @('kit-data.js')
    pdf         = @('vendor/pdfjs/pdf.min.js', 'vendor/pdfjs/pdf.worker.min.js', 'vendor/pdfjs/LICENSE-pdfjs.txt', 'vendor/pdfjs/README.txt')
}
$script:ReactFiles = @{ icons = @('Icon.tsx'); interactive = @('HoldButton.tsx', 'SearchBox.tsx', 'DropZone.tsx', 'Tabs.tsx', 'Loading.tsx', 'Composer.tsx', 'CommandButton.tsx'); charts = @('Chart.tsx'); data = @('useFileData.ts') }

function Get-UiKitColors([string]$AppRoot) {
    <# Setting uiKitColors: blue (default), neutral, or none (no colours set for the project). #>
    try { $v = "$((Get-CCBridgeConfig harness $AppRoot).uiKitColors)" } catch { $v = '' }
    if ($v -in 'neutral', 'none') { $v } else { 'blue' }
}

function Get-UiKitParts([string]$AppRoot) {
    <# The kit parts switched on: base plus interactive / charts / icons / data / pdf / react as set
       (pdf.js only with the file readers). #>
    $on = @(foreach ($p in 'interactive', 'charts', 'icons', 'data', 'pdf', 'react') { if (Test-UiKitPart $p $AppRoot) { $p } })
    if ($on -notcontains 'data') { $on = @($on | Where-Object { $_ -ne 'pdf' }) }
    @('base') + $on + @(if ((Get-UiKitColors $AppRoot) -eq 'blue') { 'palette' })
}

function Get-KitExamplesText([string]$Text, [string[]]$Parts) {
    <# The examples page without the sections of parts that are off (<!-- kit-part:NAME --> ... <!-- /kit-part:NAME -->). #>
    foreach ($p in 'interactive', 'charts', 'icons', 'data', 'pdf', 'palette') {
        if ($Parts -contains $p) { continue }
        $Text = [regex]::Replace($Text, '(?s)<!-- kit-part:' + $p + ' -->.*?<!-- /kit-part:' + $p + ' -->\r?\n?', '')
    }
    $Text
}

function Get-UiKitFolder { 'styles/kit' }

function Get-UiKitCatalog { '.streamhub/ui-kit' }

# Files that go with a kit file: its licence (the parts adapted from other projects keep their notice).
$script:Companions = @{
    'kit.js'                         = @('LICENSE-kokonutui.txt')
    'kit-charts.js'                  = @('LICENSE-bklit-ui.txt')
    'kit-icons.js'                   = @('LICENSE-lucide.txt')
    'vendor/pdfjs/pdf.min.js'        = @('vendor/pdfjs/LICENSE-pdfjs.txt', 'vendor/pdfjs/README.txt')
    'vendor/pdfjs/pdf.worker.min.js' = @('vendor/pdfjs/LICENSE-pdfjs.txt', 'vendor/pdfjs/README.txt')
}
$script:KitCssHeader = '/* Generated by the helper program from the UI kit (.streamhub/ui-kit/kit.css): the rules of the kit classes this project uses, nothing else.'

function Install-UiKit {
    <# The kit for a project: the whole kit (the parts that are on) once into its catalogue
       .streamhub/ui-kit/ (never overwritten, so the project keeps the kit version it started with),
       styles/kit/tokens.css as the project's own colours and sizes, and from then on only what the
       pages use (Update-UiKitProject). Returns the styles/kit paths added. #>
    param([Parameter(Mandatory)][string]$ProjectRoot, [Parameter(Mandatory)][string]$AppRoot)
    $src = Join-Path $AppRoot 'templates\ui-kit'
    $cat = Join-Path $ProjectRoot (Get-UiKitCatalog).Replace('/', '\')
    $parts = @(Get-UiKitParts $AppRoot)
    $files = @(foreach ($p in $parts) { if ($script:KitParts.Contains($p)) { $script:KitParts[$p] } })
    if ($parts -contains 'react') {
        foreach ($p in 'interactive', 'charts', 'icons', 'data') { if ($parts -contains $p) { $files += @($script:ReactFiles[$p] | ForEach-Object { "react/$_" }) } }
    }
    foreach ($f in $files) {
        $to = Join-Path $cat $f.Replace('/', '\')
        if (Test-Path -LiteralPath $to) { continue }
        $from = Join-Path $src $f.Replace('/', '\')
        # Colours (Settings > UI kit): the neutral palette comes from its own file.
        $colors = Get-UiKitColors $AppRoot
        if ($f -eq 'tokens.css' -and $colors -in 'neutral', 'none') { $from = Join-Path $src 'tokens-neutral.css' }
        if (-not (Test-Path -LiteralPath $from)) { continue }
        $null = New-Item -ItemType Directory -Force -Path (Split-Path $to)
        if ($f -eq 'tokens.css' -and $colors -eq 'none') {
            # No colours set: the neutral values only as a start, with a header that says they are free.
            $t = [regex]::Replace([IO.File]::ReadAllText($from), '\A/\*[\s\S]*?\*/', "/*`n  UI kit tokens, no colours set (Settings > UI kit > Colours: None): neutral starting values only,`n  so the kit's parts show. This project chooses its own colours: change any value here, or use`n  colours in the project's own CSS. Keep text readable (WCAG AA) in light and dark.`n*/")
            [IO.File]::WriteAllText($to, $t, (New-Object Text.UTF8Encoding($false)))
        }
        elseif ($f -eq 'kit-examples.html') { [IO.File]::WriteAllText($to, (Get-KitExamplesText ([IO.File]::ReadAllText($from)) $parts), (New-Object Text.UTF8Encoding($false))) }
        else { Copy-Item -LiteralPath $from -Destination $to }
    }
    $verFile = Join-Path $cat 'VERSION.txt'
    if (-not (Test-Path -LiteralPath $verFile) -and (Test-Path -LiteralPath $cat)) {
        $v = try { Get-CCBridgeVersion $AppRoot } catch { '' }
        [IO.File]::WriteAllText($verFile, "UI kit from StreamHub $v, copied $((Get-Date).ToString('yyyy-MM-dd')). The helper program takes what the pages use from here into styles/kit/.`n")
    }
    $added = @()
    # The project's own colours and sizes: copied once, then the project's to change.
    $tokens = Join-Path $ProjectRoot ((Get-UiKitFolder).Replace('/', '\') + '\tokens.css')
    $catTokens = Join-Path $cat 'tokens.css'
    if (-not (Test-Path -LiteralPath $tokens) -and (Test-Path -LiteralPath $catTokens)) {
        $null = New-Item -ItemType Directory -Force -Path (Split-Path $tokens)
        Copy-Item -LiteralPath $catTokens -Destination $tokens
        $added += "$(Get-UiKitFolder)/tokens.css"
    }
    $sync = Update-UiKitProject $ProjectRoot $AppRoot
    @($added) + @($sync.added)
}

function Get-KitUsage([string]$ProjectRoot) {
    <# What the project's pages and code use of the kit: classes (kit-NAME; a name that ends in - or _
       is a prefix, as in "kit-btn--" + variant), and kit files they refer to (styles/kit/FILE). Kit
       scripts already in styles/kit count for classes (they add markup), not for files. #>
    $root = $ProjectRoot.TrimEnd('\')
    $kitDir = (Get-UiKitFolder)
    $classes = New-Object 'System.Collections.Generic.HashSet[string]'
    $prefixes = New-Object 'System.Collections.Generic.HashSet[string]'
    $refs = New-Object 'System.Collections.Generic.HashSet[string]'
    $files = @(Get-ChildItem -LiteralPath $root -Recurse -File -Include *.html, *.htm, *.js, *.mjs, *.cjs, *.jsx, *.ts, *.tsx, *.vue, *.svelte, *.css, *.scss -ErrorAction SilentlyContinue |
        Where-Object { $_.FullName -notmatch '\\(node_modules|dist|build|\.git|\.streamhub)\\' -and $_.Length -lt 2MB } | Select-Object -First 3000)
    foreach ($f in $files) {
        $rel = $f.FullName.Substring($root.Length + 1).Replace('\', '/')
        $inKit = $rel.StartsWith("$kitDir/", [StringComparison]::OrdinalIgnoreCase)
        if ($inKit -and $rel -match '(?i)^styles/kit/(kit\.css|tokens\.css|kit-examples\.html|vendor/)') { continue }
        $t = try { [IO.File]::ReadAllText($f.FullName) } catch { '' }
        if ($t -notmatch 'kit') { continue }
        foreach ($m in [regex]::Matches($t, '(?<![\w-])kit-[A-Za-z0-9_-]+')) {
            $v = $m.Value
            if ($v -match '[-_]$') { [void]$prefixes.Add($v) } else { [void]$classes.Add($v) }
        }
        if ($inKit) { continue }
        foreach ($m in [regex]::Matches($t, '(?i)styles/kit/([\w./-]+?)(?=["''`?#)\s;,]|$)')) { [void]$refs.Add($m.Groups[1].Value) }
    }
    @{ classes = $classes; prefixes = @($prefixes); refs = @($refs) }
}

function Split-CssItems([string]$Css) {
    <# Top-level parts of a stylesheet, in order: @{ type = comment | rule | at | stmt; head; body; text }.
       Comments and strings inside are skipped when matching braces. #>
    $items = New-Object System.Collections.Generic.List[object]
    $i = 0; $n = $Css.Length
    while ($i -lt $n) {
        while ($i -lt $n -and [char]::IsWhiteSpace($Css[$i])) { $i++ }
        if ($i -ge $n) { break }
        if ($Css[$i] -eq '/' -and $i + 1 -lt $n -and $Css[$i + 1] -eq '*') {
            $e = $Css.IndexOf('*/', $i + 2); if ($e -lt 0) { $e = $n - 2 }
            $items.Add(@{ type = 'comment'; text = $Css.Substring($i, $e + 2 - $i) }); $i = $e + 2; continue
        }
        $start = $i; $par = 0
        while ($i -lt $n) {
            $c = $Css[$i]
            if ($c -eq '(') { $par++ } elseif ($c -eq ')') { $par-- }
            elseif ($c -eq '"' -or $c -eq "'") { $q = $c; $i++; while ($i -lt $n -and $Css[$i] -ne $q) { if ($Css[$i] -eq '\') { $i++ }; $i++ } }
            elseif ($par -eq 0 -and ($c -eq '{' -or $c -eq ';')) { break }
            $i++
        }
        $head = $Css.Substring($start, [Math]::Min($i, $n) - $start).Trim()
        if ($i -ge $n -or $Css[$i] -eq ';') { $items.Add(@{ type = 'stmt'; text = "$head;" }); $i++; continue }
        $b = $i + 1; $i++; $depth = 1
        while ($i -lt $n -and $depth -gt 0) {
            $c = $Css[$i]
            if ($c -eq '/' -and $i + 1 -lt $n -and $Css[$i + 1] -eq '*') { $e = $Css.IndexOf('*/', $i + 2); $i = $(if ($e -lt 0) { $n } else { $e + 2 }); continue }
            if ($c -eq '"' -or $c -eq "'") { $q = $c; $i++; while ($i -lt $n -and $Css[$i] -ne $q) { if ($Css[$i] -eq '\') { $i++ }; $i++ } }
            elseif ($c -eq '{') { $depth++ } elseif ($c -eq '}') { $depth-- }
            $i++
        }
        $items.Add(@{ type = $(if ($head.StartsWith('@')) { 'at' } else { 'rule' }); head = $head; body = $Css.Substring($b, [Math]::Max(0, $i - 1 - $b)); text = $Css.Substring($start, $i - $start) })
    }
    $items.ToArray()
}

function Split-CssSelectors([string]$Head) {
    # Selectors of a list, split at commas outside parentheses.
    $out = New-Object System.Collections.Generic.List[string]
    $par = 0; $cur = New-Object Text.StringBuilder
    foreach ($ch in $Head.ToCharArray()) {
        if ($ch -eq '(') { $par++ } elseif ($ch -eq ')') { $par-- }
        if ($ch -eq ',' -and $par -eq 0) { $out.Add($cur.ToString().Trim()); [void]$cur.Clear(); continue }
        [void]$cur.Append($ch)
    }
    if ($cur.Length) { $out.Add($cur.ToString().Trim()) }
    $out.ToArray()
}

function Test-KitSelectorUsed([string]$Selector, $Usage) {
    # Every kit class in the selector is used (or starts with a used prefix).
    foreach ($m in [regex]::Matches($Selector, '\.(kit-[A-Za-z0-9_-]+)')) {
        $c = $m.Groups[1].Value
        if ($Usage.classes.Contains($c)) { continue }
        if (@($Usage.prefixes | Where-Object { $c.StartsWith($_) }).Count) { continue }
        return $false
    }
    $true
}

function Select-KitCss {
    <# The kit's stylesheet with only the rules for the classes $Usage has: a selector list keeps the
       selectors whose kit classes are all used; @media and similar blocks keep their used rules;
       @keyframes stay when a kept rule names them. A comment goes with the rule after it, and a
       licence note with any rule of its section. #>
    param([string]$Css, $Usage, [switch]$Inner)
    $out = New-Object System.Collections.Generic.List[string]
    $frames = New-Object System.Collections.Generic.List[object]
    $note = $null; $noteOut = $false; $comment = $null
    $items = @(Split-CssItems $Css)
    for ($k = 0; $k -lt $items.Count; $k++) {
        $it = $items[$k]
        switch ($it.type) {
            'comment' {
                if ($k -eq 0 -and -not $Inner) { continue }   # the kit's own file header
                if ($it.text -match '(?i)licen[cs]e') { $note = $it.text; $noteOut = $false; $comment = $null } else { $comment = $it.text }
            }
            'stmt' { $out.Add($it.text) }
            'rule' {
                $all = @(Split-CssSelectors $it.head)
                $kept = @($all | Where-Object { Test-KitSelectorUsed $_ $Usage })
                if ($kept.Count) {
                    if ($note -and -not $noteOut) { $out.Add($note); $noteOut = $true }
                    if ($comment) { $out.Add($comment) }
                    $out.Add($(if ($kept.Count -eq $all.Count) { $it.text } else { ($kept -join ', ') + ' {' + $it.body + '}' }))
                }
                $comment = $null
            }
            'at' {
                $kf = [regex]::Match($it.head, '^@(?:-webkit-)?keyframes\s+([\w-]+)')
                if ($kf.Success) { $frames.Add(@{ name = $kf.Groups[1].Value; text = $it.text }); $comment = $null; continue }
                if ($it.head -match '^@(media|supports|container|layer)\b') {
                    $innerCss = Select-KitCss -Css $it.body -Usage $Usage -Inner:$true
                    if ($innerCss.Trim()) {
                        if ($note -and -not $noteOut) { $out.Add($note); $noteOut = $true }
                        $out.Add("$($it.head) { $($innerCss.Trim()) }")
                    }
                } else { $out.Add($it.text) }
                $comment = $null
            }
        }
    }
    $text = $out -join "`n"
    # Kept when a kept rule names them, or a page or kit script does (an animation set from code).
    foreach ($f in $frames) { if ($Usage.classes.Contains($f.name) -or $text -match ('(?<![\w-])' + [regex]::Escape($f.name) + '(?![\w-])')) { $out.Add($f.text) } }
    $out -join "`n"
}

function Get-KitFileSource([string]$ProjectRoot, [string]$AppRoot, [string]$Name) {
    <# Where a kit file comes from: the project's catalogue (Install-UiKit puts the parts that are on
       there; a part switched on later arrives at the next interface task). A React import may leave
       out the extension. $null when the catalogue has no such file. #>
    $cat = Join-Path $ProjectRoot (Get-UiKitCatalog).Replace('/', '\')
    $names = @($Name); if ($Name -notmatch '\.\w+$') { $names = @("$Name.tsx", "$Name.ts", "$Name.js") }
    foreach ($n in $names) {
        $p = Join-Path $cat $n.Replace('/', '\')
        if (Test-Path -LiteralPath $p -PathType Leaf) { return @{ name = $n; path = $p } }
    }
    $null
}

function Get-KitFileDeps([string]$Name, [string]$Text) {
    # Kit files a kit file needs: its companions, relative imports and the licence files it names.
    $dir = if ($Name.Contains('/')) { $Name.Substring(0, $Name.LastIndexOf('/')) } else { '' }
    $deps = @($script:Companions[$Name])
    foreach ($m in [regex]::Matches($Text, '(?:\bfrom\s+|\bimport\s+)["''](\.{1,2}/[^"'']+)["'']|(?:\.\./|\./)?(LICENSE-[\w.-]+\.txt)')) {
        $ref = if ($m.Groups[1].Success) { $m.Groups[1].Value } else { $m.Value }
        $parts = New-Object System.Collections.Generic.List[string]
        foreach ($seg in (($(if ($dir) { "$dir/" } else { '' }) + $ref) -split '/')) {
            if ($seg -eq '..') { if ($parts.Count) { $parts.RemoveAt($parts.Count - 1) } } elseif ($seg -and $seg -ne '.') { $parts.Add($seg) }
        }
        $deps += ($parts -join '/')
    }
    @($deps | Where-Object { $_ } | Select-Object -Unique)
}

function Update-UiKitProject {
    <# Brings styles/kit/ in line with what the project uses (after each change and at install):
       kit.css written from the catalogue with only the rules of the kit classes in use (when it is
       StreamHub's file: a kit.css without the Generated line is the project's own and stays), and
       every kit file a page or script refers to (styles/kit/FILE) copied with what it needs, and the
       icons the pages use (kit-icons.js). Returns @{ added; updated; unknown (icons) }. #>
    param([Parameter(Mandatory)][string]$ProjectRoot, [Parameter(Mandatory)][string]$AppRoot)
    $kit = Join-Path $ProjectRoot (Get-UiKitFolder).Replace('/', '\')
    $added = New-Object System.Collections.Generic.List[string]
    $updated = New-Object System.Collections.Generic.List[string]
    $usage = Get-KitUsage $ProjectRoot
    $queue = New-Object System.Collections.Generic.Queue[string]
    foreach ($r in $usage.refs) { $queue.Enqueue($r) }
    # Files the pages refer to, with what they need (run again for what the stylesheet names).
    $seen = @{}; $wantIcons = $false
    $copyQueued = {
        while ($queue.Count) {
            $name = $queue.Dequeue()
            if ($seen.ContainsKey($name.ToLowerInvariant())) { continue }
            $seen[$name.ToLowerInvariant()] = $true
            if ($name -ieq 'kit-icons.js') { $wantIcons = $true; continue }   # written by Update-KitIcons
            if ($name -in 'kit.css', 'tokens.css', 'tokens-neutral.css', 'kit-examples.html', 'VERSION.txt') { continue }
            $src = Get-KitFileSource $ProjectRoot $AppRoot $name
            if (-not $src) { continue }
            $to = Join-Path $kit $src.name.Replace('/', '\')
            if (-not (Test-Path -LiteralPath $to)) {
                $null = New-Item -ItemType Directory -Force -Path (Split-Path $to)
                Copy-Item -LiteralPath $src.path -Destination $to
                $added.Add("$(Get-UiKitFolder)/$($src.name)")
            }
            if ($src.name -match '(?i)\.(js|ts|tsx|css)$') {
                $t = try { [IO.File]::ReadAllText($to) } catch { '' }
                foreach ($d in Get-KitFileDeps $src.name $t) { $queue.Enqueue($d) }
            } else { foreach ($d in @($script:Companions[$src.name])) { if ($d) { $queue.Enqueue($d) } } }
        }
    }
    $before = $added.Count
    . $copyQueued
    # Kit scripts just copied add markup of their own: their classes count too.
    if ($added.Count -gt $before) { $usage = Get-KitUsage $ProjectRoot }
    # The stylesheet: only the rules in use.
    $cssSrc = Get-KitFileSource $ProjectRoot $AppRoot 'kit.css'
    $cssFile = Join-Path $kit 'kit.css'
    $exists = Test-Path -LiteralPath $cssFile
    $first = if ($exists) { try { (Get-Content -LiteralPath $cssFile -TotalCount 1) } catch { '' } } else { '' }
    if ($cssSrc -and (-not $exists -or "$first".StartsWith('/* Generated by the helper program from the UI kit'))) {
        $body = Select-KitCss ([IO.File]::ReadAllText($cssSrc.path)) $usage
        $text = $script:KitCssHeader + " Do not edit: use a kit class in a page and its rules are added after the change; change colours and sizes in tokens.css and put other rules in your own stylesheet. */`n" + $body.Trim() + "`n"
        $old = if ($exists) { [IO.File]::ReadAllText($cssFile) } else { '' }
        if ($old -ne $text) {
            $null = New-Item -ItemType Directory -Force -Path $kit
            [IO.File]::WriteAllText($cssFile, $text, (New-Object Text.UTF8Encoding($false)))
            if ($exists) { $updated.Add("$(Get-UiKitFolder)/kit.css") } else { $added.Add("$(Get-UiKitFolder)/kit.css") }
        }
        foreach ($d in Get-KitFileDeps 'kit.css' $body) { $queue.Enqueue($d) }
    }
    . $copyQueued
    # Icons: the base set and every icon the pages use, once a page uses one or loads kit-icons.js.
    $unknown = @()
    if (Test-UiKitPart 'icons' $AppRoot) {
        $create = $wantIcons -or @(Find-UsedIcons $ProjectRoot).Count -gt 0
        $ic = Update-KitIcons $ProjectRoot $AppRoot -Create:$create
        if ($ic.written) { if ($ic.created) { $added.Add("$(Get-UiKitFolder)/kit-icons.js") } else { $updated.Add("$(Get-UiKitFolder)/kit-icons.js") } }
        if ($ic.written -or (Test-Path -LiteralPath (Join-Path $kit 'kit-icons.js'))) {
            $lic = Join-Path $kit 'LICENSE-lucide.txt'
            $ls = Get-KitFileSource $ProjectRoot $AppRoot 'LICENSE-lucide.txt'
            if (-not (Test-Path -LiteralPath $lic) -and $ls) { Copy-Item -LiteralPath $ls.path -Destination $lic; $added.Add("$(Get-UiKitFolder)/LICENSE-lucide.txt") }
        }
        $unknown = @($ic.unknown)
    }
    @{ added = $added.ToArray(); updated = $updated.ToArray(); unknown = $unknown }
}

# Icons every project gets (common interface icons); the others come when a page uses them.
$script:BaseIcons = @('check', 'x', 'plus', 'minus', 'search', 'settings', 'trash-2', 'pencil', 'copy', 'download', 'upload', 'external-link',
    'link', 'chevron-down', 'chevron-up', 'chevron-left', 'chevron-right', 'arrow-left', 'arrow-right', 'arrow-up', 'arrow-down', 'arrow-up-down',
    'menu', 'ellipsis', 'ellipsis-vertical', 'filter', 'funnel', 'list-filter', 'calendar', 'calendar-days', 'clock', 'user', 'users', 'mail', 'bell',
    'house', 'file', 'file-text', 'folder', 'folder-open', 'info', 'circle-alert', 'triangle-alert', 'circle-check', 'circle-x', 'circle-help', 'eye',
    'eye-off', 'lock', 'lock-open', 'log-in', 'log-out', 'refresh-cw', 'rotate-ccw', 'save', 'send', 'share-2', 'star', 'heart', 'sun', 'moon',
    'loader-circle', 'chart-column', 'chart-line', 'chart-pie', 'table', 'list', 'layout-grid', 'sliders-horizontal', 'grip-vertical', 'paperclip',
    'image', 'play', 'pause', 'square', 'maximize-2', 'minimize-2', 'zoom-in', 'zoom-out', 'printer', 'globe', 'map-pin', 'phone',
    'message-square', 'tag', 'bookmark', 'flag', 'archive', 'inbox', 'database', 'server', 'cloud', 'power', 'shield', 'key', 'at-sign', 'hash',
    'percent', 'euro', 'trending-up', 'trending-down', 'activity', 'zap', 'lightbulb', 'wrench', 'panel-left', 'circle-plus', 'check-check',
    'undo-2', 'redo-2', 'history')
$script:IconCache = $null

function Get-LucideIcons([string]$AppRoot) {
    <# Every Lucide icon the kit ships: name -> the markup inside <svg> (templates/ui-kit/icons). #>
    if ($script:IconCache) { return $script:IconCache }
    $j = [IO.File]::ReadAllText((Join-Path $AppRoot 'templates\ui-kit\icons\lucide-icons.json')) | ConvertFrom-Json
    $h = @{}
    foreach ($p in $j.icons.PSObject.Properties) { $h[$p.Name] = "$($p.Value)" }
    $script:IconCache = @{ version = "$($j.version)"; icons = $h }
    $script:IconCache
}

function Find-UsedIcons([string]$ProjectRoot) {
    <# Icon names the project's pages and code use: data-kit-icon="NAME", <Icon name="NAME">, KitIcons.svg('NAME'). #>
    $names = New-Object 'System.Collections.Generic.HashSet[string]'
    $files = @(Get-ChildItem -LiteralPath $ProjectRoot -Recurse -File -Include *.html, *.htm, *.js, *.mjs, *.jsx, *.ts, *.tsx, *.vue, *.svelte -ErrorAction SilentlyContinue |
        Where-Object { $_.FullName -notmatch '\\(node_modules|dist|build|\.git|\.streamhub|styles\\kit)\\' -and $_.Length -lt 2MB } | Select-Object -First 3000)
    foreach ($f in $files) {
        $t = try { [IO.File]::ReadAllText($f.FullName) } catch { '' }
        if ($t -notmatch 'kit-icon|<Icon|KitIcons') { continue }
        foreach ($m in [regex]::Matches($t, '(?:data-kit-icon\s*=\s*|<Icon\b[^>]*?\bname\s*=\s*|KitIcons\.svg\(\s*)["'']([a-z0-9-]+)["'']')) { [void]$names.Add($m.Groups[1].Value) }
    }
    @($names)
}

function Get-IconSuggestions([string]$Name, $Known, [int]$Max = 3) {
    <# Real icon names close to one that does not exist: the most shared words first, then the shortest. #>
    $words = @($Name.Split('-') | Where-Object { $_.Length -gt 1 })
    if (-not $words.Count) { return @() }
    $scored = foreach ($k in $Known.Keys) {
        $parts = $k.Split('-')
        # A whole shared word counts 2, a word with the same first four letters (a typo) 1.
        $score = 0
        foreach ($w in $words) {
            if ($parts -contains $w) { $score += 2 }
            elseif ($w.Length -ge 4 -and @($parts | Where-Object { $_.Length -ge 4 -and $_.Substring(0, 4) -eq $w.Substring(0, 4) }).Count) { $score += 1 }
        }
        if ($score) { [pscustomobject]@{ name = $k; score = $score } }
    }
    @($scored | Sort-Object @{ e = { $_.score }; Descending = $true }, @{ e = { $_.name.Length } } | Select-Object -First $Max | ForEach-Object { $_.name })
}

function Update-KitIcons {
    <# Writes styles/kit/kit-icons.js with the base icons and every icon the project uses, when that
       set changed (or with -Create when the file is not there). Returns @{ written; created; count;
       unknown = @(@{ name; like }) } for names Lucide does not have. #>
    param([Parameter(Mandatory)][string]$ProjectRoot, [Parameter(Mandatory)][string]$AppRoot, [switch]$Create)
    $file = Join-Path $ProjectRoot ((Get-UiKitFolder).Replace('/', '\') + '\kit-icons.js')
    $exists = Test-Path -LiteralPath $file
    if (-not $exists -and -not $Create) { return @{ written = $false; created = $false; count = 0; unknown = @() } }
    $lib = Get-LucideIcons $AppRoot
    $used = @(Find-UsedIcons $ProjectRoot)
    $unknown = @($used | Where-Object { -not $lib.icons.ContainsKey($_) } | ForEach-Object { @{ name = $_; like = @(Get-IconSuggestions $_ $lib.icons) } })
    $names = @(@($script:BaseIcons) + $used | Where-Object { $lib.icons.ContainsKey($_) } | Sort-Object -Unique)
    $data = ($names | ForEach-Object { '  ' + (ConvertTo-Json $_ -Compress) + ': ' + (ConvertTo-Json $lib.icons[$_] -Compress) }) -join (",`n")
    $runtime = [IO.File]::ReadAllText((Join-Path $AppRoot 'templates\ui-kit\kit-icons-runtime.js'))
    $text = "/* Lucide icons $($lib.version) (ISC licence, see LICENSE-lucide.txt) for this project: the common ones and`n   every icon its pages use. Written by the helper program: use an icon (data-kit-icon=`"NAME`") and it is`n   added here; do not edit this file. */`nwindow.KitIconData = {`n$data`n};`n" + $runtime
    $old = if ($exists) { [IO.File]::ReadAllText($file) } else { '' }
    $written = $false
    if ($old -ne $text) {
        $null = New-Item -ItemType Directory -Force -Path (Split-Path $file)
        [IO.File]::WriteAllText($file, $text, (New-Object Text.UTF8Encoding($false)))
        $written = $true
    }
    @{ written = $written; created = (-not $exists -and $written); count = $names.Count; unknown = $unknown }
}

function Test-ReactProject([string]$ProjectRoot) {
    <# A React project: package.json names react, or the project has .jsx / .tsx files. #>
    $pkg = Join-Path $ProjectRoot 'package.json'
    if ((Test-Path -LiteralPath $pkg) -and ([IO.File]::ReadAllText($pkg) -match '"react"\s*:')) { return $true }
    [bool]@(Get-ChildItem -LiteralPath $ProjectRoot -Recurse -File -Include *.jsx, *.tsx -ErrorAction SilentlyContinue | Where-Object { $_.FullName -notmatch '\\(node_modules|dist|build|styles\\kit)\\' } | Select-Object -First 1).Count
}

function Test-UiKitInProject([string]$ProjectRoot) {
    Test-Path -LiteralPath (Join-Path $ProjectRoot ((Get-UiKitFolder).Replace('/', '\') + '\tokens.css'))
}

Export-ModuleMember -Function Get-UiKitCatalog, Get-KitUsage, Select-KitCss, Update-UiKitProject, Get-LucideIcons, Find-UsedIcons, Get-IconSuggestions, Update-KitIcons, Get-UiKitColors, Get-UiKitParts, Get-KitExamplesText, Test-ReactProject, Install-UiKit, Test-UiKitInProject, Get-UiKitFolder
